name: Get images from google photos

on:  
  schedule:
    - cron: '40 7 * * 1,5'
  workflow_dispatch:
  
jobs:
  get-photos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: Skux4life/getPhotos
          token: ${{ secrets.PAT }}
          path: functions
          
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{ secrets.PAT }}

      - name: Set-up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - name: run
        run: go run functions/getPhotos.go
        
      - name: commit changes and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd main
          git config user.name "Skux4life bot"
          git config user.email "mattellis1234@gmail.com"
          git status
          git add -A
          git commit -m "add new photos"
          git status
          git push origin main
        
          
