name: Get images from google photos

on:
  workflow_dispatch
  
jobs:
  get-photos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: Skux4life/getPhotos
          token: ${{ secrets.PAT }}
          path: functions
          
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set-up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.4' # The Go version to download (if necessary) and use.
      - name: run
        run: go run functions/getPhotos.go
        
      - name: create pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update images
          title: Update Images
          body: Add new images
          branch: update-images
          base: main
